### ISSUE TITLE
Newsletter signup form doesn't show confirmation

### ISSUE THREAD

**Issue by nuel** [evadecker/eva.town#319]
Howdy 🤠

The newsletter form on the homepage seems to send out a request (I did get the email from Buttondown) but the interface hangs on "dialing up" / "connecting wires" / etc.

Love your site btw!!

**Comment by evadecker** [comment]
Oh I just saw this!! Thank you for filing @nuel, I'll take a look at this soon :)

Your site is great too!!

**Comment by evadecker** [comment]
This has been fixed! Thanks for reporting!
