### ISSUE TITLE
RSS feed?

### ISSUE THREAD

**Issue by gBasil** [evadecker/eva.town#422]
It would be nice to have an RSS feed for the Garden section.

**Comment by evadecker** [comment]
Great recommendation! I'll look into adding one.

**Comment by evadecker** [comment]
Added an RSS feed! https://eva.town/rss.xml

I don't use RSS myself so let me know if there's anything off or buggy and I'll make another update :)

**Comment by gBasil** [comment]
Thanks! :D The `<link>` with the `truerss.xml` link seems to go to a 404, but the link in the bottom footer (`rss.xml`) works.

**Comment by evadecker** [comment]
Oops, silly mistake, should be fixed now!
