### ISSUE TITLE
'Shoo Sam' button won’t appear again

### ISSUE THREAD

**Issue by 22Xy** [evadecker/eva.town#544]
cute feature! but i noticed that if the 'Shoo Sam' button is pressed, the next time i want to clear the stickers, the button doesn’t appear. not sure if it's a bug or a feature tho lol
![image](https://github.com/user-attachments/assets/a8e15e67-f9fc-45a5-a6bc-9531ea166e96)
![image](https://github.com/user-attachments/assets/0ae5dc7a-541b-433d-9431-c9b51df6a86e)

**Comment by evadecker** [comment]
Oh! You're right, thanks for reporting this. I'll push a fix soon :)

**Comment by evadecker** [comment]
@22Xy You can now shoo Sam as many times as you want 🧹 

The animation for the shoo button was also jittery so I smoothed that out, too.

**Comment by 22Xy** [comment]
> @22Xy You can now shoo Sam as many times as you want 🧹
> 
> The animation for the shoo button was also jittery so I smoothed that out, too.

fantastic!
